apiVersion: batch/v1
kind: CronJob
metadata:
    name: pipelines-cronjob-spring-petclinic
    labels:
        app.kubernetes.io/managed-by: tkn-dsl
        tkn-dsl.dev/pipeline: spring-petclinic
spec:
    concurrencyPolicy: Forbid
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - args:
                            - |-
                              curl -s -X POST \
                                -H "Content-Type: application/json" \
                                "http://pipelines-as-code-controller.openshift-pipelines.svc.cluster.local:8080/incoming" \
                                -d '{
                                  "repository": "'"${REPOSITORY}"'",
                                  "branch": "main",
                                  "pipelinerun": "spring-petclinic",
                                  "secret": "'"${WEBHOOK_SECRET}"'",
                                  "namespace": "'"${NAMESPACE}"'"
                                }'
                          command:
                            - /bin/sh
                            - -c
                          env:
                            - name: PAC_CONTROLLER_URL
                              value: http://pipelines-as-code-controller.openshift-pipelines.svc.cluster.local:8080
                            - name: REPOSITORY
                              value: spring-dsl-test
                            - name: WEBHOOK_SECRET
                              valueFrom:
                                secretKeyRef:
                                    key: secret
                                    name: spring-petclinic-incoming-secret
                            - name: NAMESPACE
                              valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                          image: registry.redhat.io/ubi9
                          name: trigger
                    restartPolicy: OnFailure
    schedule: '* * * * *'
